from AccessSalaryImporter import Importer as AccessSalaryImporter
from FirstAccountImporter import Importer as FirstAccountImporter
from AmexCSVImporter import Importer as AmexCSVImporter
from HSBCCCImporter import Importer as HSBCCCImporter